name: generate-kyfbg-string
run-name: ${{ github.actor }} is updating "Know Your Friend Boardgame" data.

on: workflow_dispatch

env:
  SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  KYFBG_SHEETID: ${{ vars.KYFBG_SHEETID }}

jobs:
  fetch-and-generate-data:
    runs-on: ubuntu-latest
    environment: master

    steps:
    - uses: actions/checkout@v3

    - name: Set pnpm up
      uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

    - name: Fetch and generate the data
      run: pnpm run build:kyfbg