name: generate-kyfbg-string
run-name: ${{ github.ACTOR }} is updating "Know Your Friend Boardgame" data.

on: workflow_dispatch

env:
  SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  KYFBG_SHEETID: ${{ vars.KYFBG_SHEETID }}

jobs:
  fetch-and-generate-data:
    runs-on: ubuntu-latest
    environment: master

    steps:
    - uses: actions/checkout@v3

    - name: Set pnpm up
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: true

    - name: Set permission
      run: chmod +rw ./data/KnowYourFriendBoardgame/

    - name: Fetch and generate the data
      run: pnpm run build:kyfbg

    - name: Commit changes
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m '${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}'
          git push
